stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/diabetes.csv
      - src/preprocess.py
    params:
      - preprocess
    outs:
      - data/processed/data.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/data.csv
      - src/train.py
    params:
      - train
      - tuning
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.pkl
      - data/processed/data.csv
      - src/evaluate.py
    params:
      - evaluate
    metrics:
      - metrics/accuracy.json:
          cache: false
      - metrics/scores.json:
          cache: false
      - metrics/confusion_matrix.json:
          cache: false
      - metrics/classification_report.json:
          cache: false
