preprocess:
  input: data/raw/diabetes.csv
  output: data/processed/data.csv

train:
  data: data/processed/data.csv
  models: models/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5

tuning:
  n_estimators: [50, 100, 150]
  max_depth: [5, 10, 15]
  min_samples_split: [2, 5]
  min_samples_leaf: [1, 2]
  max_features: ["sqrt", "log2"]

evaluate:
  model: models/model.pkl
  test_data: data/processed/data.csv
  metrics: metrics
